spring:
  jpa:
    show-sql: true #쿼리문 출력하게 함
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

  #접속 시 사용할 JDBC URL
  datasource:
    url: jdbc:h2:mem:testdb

  #H2 콘솔 활성화
  h2:
    console:
      enabled: true

jwt:
  issuer: diaryMoodAnalyzer@gmail.com
  secret_key: someSecretKeyToCreateJwt